### ISSUE TITLE
The result of ComposeAE on FashionIQ dataset

### ISSUE THREAD

**Issue by huubinh49** [ecom-research/ComposeAE#20]
How did you calculate your model performance on 3 categories of FashionIQ dataset?
By averaging or getting maximum performance on those categories?

**Comment by ecom-research** [comment]
Hi,

First thing to note is that the results are on the validation set of the dataset. The test set was not revealed to the public at the time of writing of the paper.

Regarding how the evaluation is made, please refer to the evaluation code. Specifically, this part will answer your query: https://github.com/ecom-research/ComposeAE/blob/271865ecad1e0efb101a6a2be4915ea7dd263e61/test_retrieval.py#L123
