### ISSUE TITLE
Comparison with CVPR2020 VAL on FashionIQ

### ISSUE THREAD

**Issue by BrandonHanx** [ecom-research/ComposeAE#9]
Hi all, thanks for your work.

I wonder why not compare your result with [CVPR2020 paper named VAL](https://openaccess.thecvf.com/content_CVPR_2020/html/Chen_Image_Search_With_Text_Feedback_by_Visiolinguistic_Attention_Learning_CVPR_2020_paper.html)? 

It seems like VAL is published earlier and performed better than you on FashionIQ. Does your work have a different setting with VAL?

Thanks in advance. Please point out if I am wrong.

**Comment by ecom-research** [comment]
We did not know this work. We searched for works on FashionIQ but did not find any relevant research papers. Perhaps, it was done parallel to our work. Nonetheless, the work seems interesting.
